plugins {
	id 'java'
	alias(libs.plugins.springboot)
	alias(libs.plugins.spring.dependency.management)
	alias(libs.plugins.plugin.spotless)
}

group = 'br.petroedge'
version = '0.0.1'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation(libs.springboot.web)
	implementation(libs.springboot.webclient)
	implementation(libs.springboot.restclient)
	implementation(libs.springboot.actuator)
	implementation(libs.springboot.security)
	implementation(libs.springboot.oauth2)
	implementation(libs.springboot.jpa)
	implementation(libs.springboot.mail)
	implementation(libs.liquibase.core)

	implementation(libs.mysql.connector)
	implementation(libs.slf4j)
	implementation(libs.springdoc.openapi)

	compileOnly(libs.lombok)
	annotationProcessor(libs.lombok)

	testImplementation(libs.springboot.test)
	testImplementation(libs.swagger.parser)
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	java {
		target '**/*.java'
		palantirJavaFormat('2.71.0')
		removeUnusedImports()
		trimTrailingWhitespace()
		endWithNewline()
		targetExclude('**/build/**', '**/target/**')
	}
	groovyGradle {
		target '**/*.gradle'
		greclipse()
		trimTrailingWhitespace()
		endWithNewline()
	}
}

tasks.named('check') {
	dependsOn spotlessCheck
}
