services: 
  app:
    image: operational-response-service:0.0.1
    container_name: oprs-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=api
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/oprs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=oprs
      - SPRING_DATASOURCE_PASSWORD=oprs_pass
      - SPRING_MAIL_HOST=oprs-mailpit
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=
      - SPRING_MAIL_PASSWORD=
    networks:
      oprs-dev-net:

  mailpit:
    image: axllent/mailpit:latest
    container_name: oprs-mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      oprs-dev-net:
        aliases:
          - oprs-mailpit

  database:
    container_name: oprs-db
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=oprs
      - MYSQL_USER=oprs
      - MYSQL_PASSWORD=oprs_pass
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      oprs-dev-net:
        aliases:
          - oprs-db

volumes:
  mailpit_data:
  mysql_data:

networks:
  oprs-dev-net:
    external: true
    name: oprs-dev-net
